### PR TITLE
Start11 v2 Polish Translation

### PR DESCRIPTION
**Pull request by BartoszJedynak**

### CODE REVIEW

**Comment by magnumpci** [comment]
@BartoszJedynak , I just wanted to let you know that I recently posted all the updated languages to the Start11 v2 repo:

https://github.com/StardockCorp/Stardock-Software-Localization/blob/main/Start-Products/Start11%20v2/README.md

If you want to cancel this pull request and work from those, let me know.

Thanks for the time and effort, @BartoszJedynak .

Sean Drohan
Stardock Product Lifecycle Manager

**Comment by BartoszJedynak** [comment]
everything is fine, on Stardock my nickname is Putridumx ;)

**Comment by magnumpci** [comment]
@BartoszJedynak ,

1st, thank you again for your time and work.

I did want to ask, however.  The en.lng file for Start11 v2 has 872 lines while your translation has 1243, a 371 line difference.  Can you say why that is or...?

Also, I am going to close this request until I can upload all the language files again (likely just later today).  I need to so as to fix the encoding issue (UTF-16 vs UTF-8) that GitHub has presented us.  It maybe prudent to get those updated files, again, later today or tomorrow.

Again, thanks for your time and patience.

Sean Drohan
Stardock Product Lifecycle Manager

**Comment by BartoszJedynak** [comment]
> @BartoszJedynak ,
> 
> 1. Jeszcze raz dziękuję za poświęcony czas i pracę.
> 
> Chciałem jednak zapytać. Plik en.lng dla start11 v2 ma 872 wiersze, podczas gdy twoje tłumaczenie ma 1243, co stanowi różnicę 371 wierszy. Czy możesz powiedzieć, dlaczego tak jest, albo...?
> 
> Ponadto zamierzam zamknąć tę prośbę, dopóki nie będę mógł ponownie przesłać wszystkich plików językowych (prawdopodobnie jeszcze dzisiaj). Muszę, aby rozwiązać problem z kodowaniem (UTF-16 vs UTF-8), który przedstawił nam GitHub. Być może rozsądnie byłoby pobrać te zaktualizowane pliki jeszcze dziś lub jutro.
> 
> Jeszcze raz dziękuję za poświęcony czas i cierpliwość.
> 
> Sean Drohan Stardock Kierownik ds. cyklu życia produktu



> @BartoszJedynak ,
> 
> 1st, thank you again for your time and work.
> 
> I did want to ask, however. The en.lng file for Start11 v2 has 872 lines while your translation has 1243, a 371 line difference. Can you say why that is or...?
> 
> Also, I am going to close this request until I can upload all the language files again (likely just later today). I need to so as to fix the encoding issue (UTF-16 vs UTF-8) that GitHub has presented us. It maybe prudent to get those updated files, again, later today or tomorrow.
> 
> Again, thanks for your time and patience.
> 
> Sean Drohan Stardock Product Lifecycle Manager

Hi, on pl.lng not all strings have been translated, so that why my translation has 1243 lines not 872.

**Pull request closed without merging**
