### PR TITLE
Updated Swedish Start11 translation

### PR DESCRIPTION
**Pull request by rickard67**
Swedish Start11 v2 translation.
Added missing strings and fixed some issues.

Regards,
Rickard Johansson (rj79048)

### CODE REVIEW

**Comment by magnumpci** [comment]
@rickard67 , thank you for this but I was wondering if you might have wanted to do work on the newly release Start11 v2 translations:

https://github.com/StardockCorp/Stardock-Software-Localization/blob/main/Start-Products/Start11%20v2/README.md

If you need a license, PM me and Ill get you a key:
https://forums.stardock.com/user/4871965

Sean Drohan
Stardock Product Lifecycle Manager

**Comment by magnumpci** [comment]
Hmmm, it seems you have included the v2 translations.  I will review this.

Thank you again, @rickard67 

Sean Drohan
Stardock Product Lifecycle Manager

**Comment by rickard67** [comment]
My user name in the Startdock forum is rj79048, my GitHub handle is @rickard67 and my real name is Rickard Johansson.
(So @rickard67 is not a new translator. It's just me...)

I'll try to add my name when adding pull requests in the future...

Regards,
Rickard Johansson (rj79048)

**Comment by magnumpci** [comment]
All,

This is going to be sent to all of the ones that have submitted pull requests for the various apps over the last several weeks (and ty all again for them).

Because the lang files need to be encoded as UTF-16 LE, there are issues with getting a proper diff in GitHub (GH) as it sees them as binaries:

https://cdn.stardock.us/support/uploads/msedge_2023-12-06_12-26-41.png

We believe we have a workaround and have changed the .gitattributes file to accommodate it.  However, for it to all work, we need to re-commit all the lang files so that GH reads them properly.  Thus, this is what will happen.

I will merge your current pull request
I will delete \ recommit all lang files 
I will test that the change works

Again, we really do appreciate the time and effort you all have made.

Sean Drohan
Stardock Product Lifecycle Manager

**Pull request merged**
